'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class viewProduct

    '''<summary>
    '''txtMeatProductID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMeatProductID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DropDownListMeat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownListMeat As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtmeatprice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtmeatprice As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtmeatquantity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtmeatquantity As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtmeatamount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtmeatamount As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnmeatBuy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnmeatBuy As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtChickenProductID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtChickenProductID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DropDownListChicken control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownListChicken As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtChickenPrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtChickenPrice As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtChickenQuantity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtChickenQuantity As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtChickenAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtChickenAmount As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnChickenBuy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnChickenBuy As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtFishProductID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFishProductID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DropDownListFish control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownListFish As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtFishprice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFishprice As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtFishQuantity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFishQuantity As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtFishamount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFishamount As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnFishBuy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFishBuy As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtVanillaProductID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVanillaProductID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DropDownListVanilla control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownListVanilla As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtvanillaPrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtvanillaPrice As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtvanillaQuantity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtvanillaQuantity As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtvanillaAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtvanillaAmount As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnvanillaBuy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnvanillaBuy As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtDrinksProductID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDrinksProductID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DropDownListDrinks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownListDrinks As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtDrinkPrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDrinkPrice As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDrinkQuantity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDrinkQuantity As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDrinkAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDrinkAmount As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnDrinkBuy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDrinkBuy As Global.System.Web.UI.WebControls.Button
End Class
